services:
  pyspark:
    build: ./docker
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: >
      start-notebook.sh
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --NotebookApp.password=''